### PR TITLE
chore(deps): upgrade to typescript 3.9.3

### PR DESCRIPTION
**Pull request by RomainMuller**
## Commit Message
chore(deps): upgrade to typescript 3.9.2 (#1664)

BREAKING CHANGES: The TypeScript compiler was upgraded from 3.8 to 3.9,
which includes a few breaking changes. More information can be found on
the TypeScript 3.9 Announcement page:
https://devblogs.microsoft.com/typescript/announcing-typescript-3-9-beta/#breaking-changes

## End Commit Message
---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

### CODE REVIEW

**Comment by RomainMuller** [comment]
Note that this includes a workaround for microsoft/TypeScript#38542

**Comment by rix0rrr** [comment]
Fine with accepting this. This caught my eye in the list of breaking changes:

> Getters/Setters are No Longer Enumerable

This might have implications for jsii.

**Comment by RomainMuller** [comment]
> Fine with accepting this. This caught my eye in the list of breaking changes:
> 
> > Getters/Setters are No Longer Enumerable
> 
> This might have implications for jsii.

In fact it doesn't... This is a change in the emitted JS code only; in case the compiler is configured to target `ES5` or `ES2015` -- but `jsii` mandates an `ES2018` target.

**Comment by RomainMuller** [comment]
> Since TS contains breaking changes, technically jsii should bump breaking changes? (And therefore CDK should bump breaking changes?)

I'm not sure those breaking changes are actually problematic. The ones that affect us are either TypeScript generating less surprising code in some fringe cases, and type checking improvements that may find previously unseen bugs.

**Comment by RomainMuller** [comment]
Leaving as `pr/do-no-merge` until I get a chance to try to build `aws/aws-cdk` with it to assess whether the breaking changes are material or not (expecting they're not).

**Pull request closed without merging**
