### PR TITLE
chore(python): documentation improvements

### LINKED ISSUE #474: Python: type references to nested types cannot be resolved
While generating docs, (forward) type references in the `CfnFooProps` cannot be resolved, and so are not displayed properly.

### PR DESCRIPTION
**Pull request by RomainMuller**
Improved the documentability of generated Python code by reducing the
use of forward references through keeping track of types that were
already emitted; and by emitting the kind of forward reference that `sphinx`'
`autodoc` extension is able to resolve (forward references within a sub-package
must be relative to that sub-package; and nested declarations can not
use their surrounding type's name in forward references (those must be relative
to the surrounding type's context).

Additionally, removed duplicated headings that were generated for
documentation segments (`see`, `returns`, ...), as those were causing
redundant content to appear on the generated docsite.

This completely removes `ForwardRef` instances from the Python
reference documentation (as was checked by issuing a recursive
`grep` on the generated documentation).

Fixes #474
Related #1919 

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

### CODE REVIEW

**Comment by RomainMuller** [comment]
The Python reference documentation generated for some recent release of the CDK is accessible here: https://d1ij3ht5b3pps1.cloudfront.net/

This link will remain valid until this PR is merged.

**Comment by eladb** [comment]
Weirdness:

**Comment by eladb** [comment]
Another empty bullet: https://d1ij3ht5b3pps1.cloudfront.net/aws_cdk.aws_sns/Topic.html#aws_cdk.aws_sns.Topic.add_subscription

**Comment by RomainMuller** [comment]
> Another empty bullet: https://d1ij3ht5b3pps1.cloudfront.net/aws_cdk.aws_sns/Topic.html#aws_cdk.aws_sns.Topic.add_subscription

This is no different from the currently published documentation: https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_sns/Topic.html#aws_cdk.aws_sns.Topic.add_subscription

The reason is the parameter is simply not documented at all (but it is still represented in the Python docs, because... otherwise you don't get to know what it's type is):
- https://github.com/aws/aws-cdk/blob/451200e3dba6b8d80bc8396dc0b7d4d84f29cb56/packages/%40aws-cdk/aws-sns/lib/topic-base.ts#L25-L28
- https://github.com/aws/aws-cdk/blob/451200e3dba6b8d80bc8396dc0b7d4d84f29cb56/packages/%40aws-cdk/aws-sns/lib/topic-base.ts#L62-L65

**Comment by eladb** [comment]
> > Another empty bullet: https://d1ij3ht5b3pps1.cloudfront.net/aws_cdk.aws_sns/Topic.html#aws_cdk.aws_sns.Topic.add_subscription
> 
> 
> 
> This is no different from the currently published documentation: https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_sns/Topic.html#aws_cdk.aws_sns.Topic.add_subscription
> 
> 
> 
> The reason is the parameter is simply not documented at all (but it is still represented in the Python docs, because... otherwise you don't get to know what it's type is):
> 
> - https://github.com/aws/aws-cdk/blob/451200e3dba6b8d80bc8396dc0b7d4d84f29cb56/packages/%40aws-cdk/aws-sns/lib/topic-base.ts#L25-L28
> 
> - https://github.com/aws/aws-cdk/blob/451200e3dba6b8d80bc8396dc0b7d4d84f29cb56/packages/%40aws-cdk/aws-sns/lib/topic-base.ts#L62-L65

I get why this is happening, but it shouldn't look like that nevertheless

**Comment by RomainMuller** [comment]
> I get why this is happening, but it shouldn't look like that nevertheless

I'm trying to avoid overloading PRs with too many features.

Are you asking me to fix this in that PR, too? Who are you and what have you done to @eladb?

**Review by rix0rrr — APPROVED** [review]

**Pull request merged**
