### PR TITLE
feat(pacmak): update Python dependency `typeguard` to more modern version

### PR DESCRIPTION
**Pull request by iwanbolzern**
Updated Python typeguard dependency to reasonable new version.

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

### CODE REVIEW

**Comment by iwanbolzern** [comment]
Dear jsii maintainers,

Any chance that we can get this merged soon?

Thank you and all the best,
Iwan

**Comment by mrgrain** [comment]
Thanks for raising the PR.  This will needs an update to the snapshot tests.

**Comment by sam-goodwin** [comment]
Oh cool, good to see this in progress. Thanks @iwanbolzern!!

I opened an Issue for this just yesterday, didn't see the PR: https://github.com/aws/jsii/issues/4469

**Comment by sam-goodwin** [comment]
Have opened a PR that updates the generated code and updates the snapshot tests: https://github.com/aws/jsii/pull/4470

**Comment by iwanbolzern** [comment]
Thanks @sam-goodwin for looking into this! I'm going to close this PR in favor of yours.

**Pull request closed without merging**
