### PR TITLE
fix(python): bin script python support, test argument passing

### PR DESCRIPTION
**Pull request by jmalins**
Corrects multiple issues with running `bin` scripts from python.

These were discovered in the context of this `projen` issue: https://github.com/projen/projen/issues/2103

 - Corrects broken argument marshaling to binary scripts introduced in #3694
 - Exposes exit code and stderr from script execution instead of failing silently

Additionally, adds more robust test coverage of passing arguments to `bin` scripts.

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

### CODE REVIEW

**Comment by jmalins** [comment]
The tests are currently failing due to the `jsii-calc/bin/run` not being executable in the extracted tarball.

```yaml
status: 126
stderr: "/bin/sh: 1: /tmp/jsii-kernel-4QI5As/node_modules/jsii-calc/bin/run: Permission denied"
```

I'm still trying to troubleshoot this. Running `npm pack` manually produces a tarball with correct `-rwxr-xr-x` permissions.

**Comment by jmalins** [comment]
Hi @RomainMuller, is it acceptable to leave Windows bin invoke functionality partially implemented? It appears that is the current state of `jsii-pacmak`, as it doesn't generate executables scripts for Windows, which would need to be added.

Other than that, I believe this PR is ready.

**Comment by RomainMuller** [comment]
@jmalins if that is currently broken I'm not going to demand you fix it of course 😅

**Review by RomainMuller — APPROVED** [review]

**Review by RomainMuller — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
