### PR TITLE
docs: fix typo in 2-type-system.md

### PR DESCRIPTION
**Pull request by eltociear**
arbitary -> arbitrary

### CODE REVIEW

**Review by BenChaimberg — APPROVED** [review]

**Review by RomainMuller — APPROVED** [review]

**Comment by RomainMuller** [comment]
@all-contributors add @BenChaimberg for docs

**Comment by RomainMuller** [comment]
@all-cotributors add eltociear for docs

**Comment by RomainMuller** [comment]
@all-contributors add @eltociear for docs

**Review by skinny85 — APPROVED** [review]
Thanks for the contribution @eltociear!

**Pull request merged**
