### PR TITLE
feat(jsii): enable source maps for declaration files

### PR DESCRIPTION
**Pull request by andrestone**
Generates [declaration maps](https://www.typescriptlang.org/tsconfig#declarationMap) when compiling.

This is useful to help navigate source files when developing against a JSII library's repo (e.g using yarn link).

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

### CODE REVIEW

**Comment by RomainMuller** [comment]
Hey @andrestone - can you elaborate on why you're making this change?

Depending on the rationale (you might have thought into this a bit more than I have), I wonder if we should just always turn the flag on, instead of making it customizable? I doubt it's very expensive to have, and it's "strongly recommended" by the TypeScript documentation...

**Comment by andrestone** [comment]
Sorry I missed your first question. This is basically to help navigate source files when developing.

**Comment by RomainMuller** [comment]
Are these emitted as separate files? If so, they could be added to `.npmignore`...

In any case, I don't think there is much harm in actually shipping the declarations... If the corresponding sources aren't present, IDE integrations would just fall back to the "usual" process...

They could be seen as dead-weight... but I doubt that'd be very heavy, so maybe this can be ignored?

**Comment by andrestone** [comment]
Yes, they're separate files with the extension`.d.ts.map`. And yes, language servers would fall back to `d.ts` files so it should be ok. Gonna make the changes.

**Comment by andrestone** [comment]
@RomainMuller I'm unsure if we rely on `tsconfig-base.json` for anything else related to the compiler, but I've added the option there too [as recommended](https://www.typescriptlang.org/tsconfig#:~:text=You%20should%20strongly%20consider%20turning%20this%20on%20if%20you%E2%80%99re%20using%20project%20references.) since we're using project references in JSII itself (hence the many map files).

**Comment by andrestone** [comment]
> That's okay, but you should not check in all the `.d.ts.map` files :)

Of course! I think I checked the root `.gitignore` entries for `*.d.ts` and since I couldn't find it there I assumed the declarations were checked in for some reason which doesn't make sense.

Should be ok now.

**Comment by andrestone** [comment]
Hey @RomainMuller! Sorry for the ping, just wanted to make sure there isn't anything else I could do here.

**Review by RomainMuller — APPROVED** [review]

**Comment by RomainMuller** [comment]
Hey @andrestone -- sorry I got caught up in other stuff and forgot to check back here...

At this stage, this looks good to go for me.
We can let Mergify handle it from there (unless PR validations somehow break).

**Pull request merged**
