### PR TITLE
docs: correct spelling of traditional

### PR DESCRIPTION
**Pull request by benfarr**
---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

### CODE REVIEW

**Review by benfarr — COMMENTED** [review]
spelling typo fix looks good. tiny contribution, getting my feet wet in the project. awesome documentation, overall. thanks for your work and efforts to keep this clean. can't wait to dive in.

**Comment by RomainMuller** [comment]
There is no contribution too small :) Thanks for your help!

@all-contributors add @benfarr for docs

**Review by RomainMuller — APPROVED** [review]

**Comment by RomainMuller** [comment]
@MergifyIO refresh

**Comment by benfarr** [comment]
> There is no contribution too small :) Thanks for your help!
> 
> @all-contributors add @benfarr for docs

Rock on. Looking forward to digging in. Thanks again!

**Pull request merged**
