### PR TITLE
[WIP] Ruby support

### PR DESCRIPTION
**Pull request by eladb**
This is a WIP pull request for jsii Ruby support.

### Compliance

- [x] primitiveTypes
- [x] dates
- [x] collectionTypes
- [x] dynamicTypes
- [x] unionTypes
- [x] createObjectAndCtorOverloads
- [x] getSetPrimitiveProperties
- [x] callMethods
- [x] unmarshallIntoAbstractType
- [x] getAndSetNonPrimitiveProperties
- [x] getAndSetEnumValues
- [x] useEnumFromScopedModule
- [x] undefinedAndNull
- [x] arrays
- [x] maps
- [x] dataTypes
- [x] unionPropertiesWithBuilder (skip)
- [x] exceptions
- [x] unionProperties
- [x] subclassing
- [x] testJSObjectLiteralToNative
- [x] testFluentApiWithDerivedClasses
- [x] creationOfNativeObjectsFromJavaScriptObjects
- [x] asyncOverrides_callAsyncMethod
- [x] asyncOverrides_overrideAsyncMethod
- [x] asyncOverrides_overrideAsyncMethodByParentClass
- [x] asyncOverrides_overrideCallsSuper
- [x] asyncOverrides_twoOverrides
- [ ] asyncOverrides_overrideThrows
- [ ] syncOverrides
- [ ] propertyOverrides_get_set
- [ ] propertyOverrides_get_calls_super
- [ ] propertyOverrides_set_calls_super
- [ ] propertyOverrides_get_throws
- [ ] propertyOverrides_set_throws
- [ ] propertyOverrides_interfaces
- [ ] interfaceBuilder
- [ ] syncOverrides_callsSuper
- [ ] fail_syncOverrides_callsDoubleAsync_method
- [ ] fail_syncOverrides_callsDoubleAsync_propertyGetter
- [ ] fail_syncOverrides_callsDoubleAsync_propertySetter
- [ ] testInterfaces
- [ ] testNativeObjectsWithInterfaces
- [ ] testLiteralInterface
- [ ] testInterfaceParameter
- [ ] structs_stepBuilders
- [ ] structs_buildersContainNullChecks
- [ ] structs_serializeToJsii
- [ ] statics
- [ ] consts
- [ ] reservedKeywordsAreSlugifiedInMethodNames
- [ ] nodeStandardLibrary
- [ ] returnAbstract
- [ ] doNotOverridePrivates_method_public
- [ ] doNotOverridePrivates_method_private
- [ ] doNotOverridePrivates_property_by_name_private
- [ ] doNotOverridePrivates_property_by_name_public
- [ ] doNotOverridePrivates_property_getter_public
- [ ] doNotOverridePrivates_property_getter_private
- [ ] classWithPrivateConstructorAndAutomaticProperties
- [ ] nullShouldBeTreatedAsUndefined

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by floehopper** [comment]
@eladb Are you still working on this branch? I'd be willing to contribute to the Ruby implementation, but I'm struggling to get a development environment setup so I can run the relevant tests. Do you have any advice?

**Comment by eladb** [comment]
@floehopper I've been working on this on the back burner, and would love contributions!

Ideally our contribution guide should explain how to setup an environment, but it might be outdated. What are the specific issues you are running into?

**Comment by floehopper** [comment]
@eladb Thanks for the encouragement. Since my setup woes are orthogonal to this PR, I've created [a new issue](https://github.com/awslabs/jsii/issues/354) to ask for help.

**Comment by floehopper** [comment]
@eladb 

> Also, would you like to set up some time to chat over video on this work? The repo documentation is very scarce and I'd love to give you some context and pointers on how to tackle this... It's quite hairy...

Yeah, I'd be up for that. Although I think I'd like to dig into the code a little bit first just to orient myself and make any chat as useful as possible. Also I should mention that my experience is more in the Ruby end of things than the TypeScript end!

**Comment by eladb** [comment]
@floehopper no worries. hit me up here or on Gitter and we'll set up some time

**Comment by rix0rrr** [comment]
I'm going to close this PR until we have room to pick it up again. Feel free to reopen if someone thinks this was closed in error.

**Pull request closed without merging**
